# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - AINotesApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Create deployment package
      run: |
        mkdir -p deploy
        cp -r .next deploy/
        cp -r public deploy/
        cp -r src deploy/
        cp package*.json deploy/
        cp next.config.ts deploy/
        cp tsconfig.json deploy/
        cp components.json deploy/
        cp eslint.config.mjs deploy/
        cp postcss.config.mjs deploy/
        cp next-env.d.ts deploy/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: node-app
        path: deploy/

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'AINotesApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5d009f08735d485780ab77fe782b702f }}
        package: deploy/